version: '3.9'

services:

  rabbitmq1:
    image: rabbitmq:3-management
    container_name: node1-rabbitmq
    hostname: rabbitmq1
    volumes:
      - ./config/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./config/rabbitmq/rabbitmq-definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/data-node1/:/var/lib/rabbitmq/
      - ./rabbitmq/log-node1/:/var/log/rabbitmq
    networks:
      - rabbitmq_cluster
    env_file:
      - ./.env.prod

  rabbitmq2:
    image: rabbitmq:3-management
    container_name: node2-rabbitmq
    hostname: rabbitmq2
    depends_on:
      - rabbitmq1
    volumes:
      - ./config/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./config/rabbitmq/rabbitmq-definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/data-node2/:/var/lib/rabbitmq/
      - ./rabbitmq/log-node2/:/var/log/rabbitmq
    networks:
      - rabbitmq_cluster
    env_file:
      - ./.env.prod

  rabbitmq3:
    image: rabbitmq:3-management
    container_name: node3-rabbitmq
    hostname: rabbitmq3
    depends_on:
      - rabbitmq1
    volumes:
      - ./config/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./config/rabbitmq/rabbitmq-definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/data-node3/:/var/lib/rabbitmq/
      - ./rabbitmq/log-node3/:/var/log/rabbitmq
    networks:
      - rabbitmq_cluster
    env_file:
      - ./.env.prod
    
  haproxy:
    image: haproxy:1.7
    container_name: load-balancer
    volumes:
      - ./config/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - rabbitmq_cluster

networks:
  rabbitmq_cluster:
    driver: bridge